### ISSUE TITLE
config.dsl miconfiguration

### ISSUE THREAD

**Issue by jbe99** [ergon/airlock-helm-charts#13]
https://github.com/ergon/airlock-helm-charts/blob/28ca5801e8c63bf2cb4537bde607f1866a86a02d/charts/microgateway/templates/configmap.yaml#L104

Change to:
`config.yaml: {{ toYaml $config.dsl | nindent 4 }}`

Test Values file:
```
config:
    dsl: |
      license_file: /secret/config/license
      session:
        encryption_passphrase_file: /secret/config/passphrase
      log:
        level: info
      expert_settings:
        apache: |
          LogLevel warn
        
      apps: 
        - virtual_host:
            hostname: entry2
          backend:
            hostname: backend2
          mappings:
            - name: app2.1
              entry_path: /app2_1
              backend_path: /back/app2_1
            - name: app2.2
              entry_path: /app2_2
              backend_path: /back/app2_2

```
