### ISSUE TITLE
[Bug] Route passthrough

### ISSUE THREAD

**Issue by jbe99** [ergon/airlock-helm-charts#26]
## Description
There is an error in the documentation. 

## Expected documentation
```
    tls:
      enabled: true
      termination: passthrough
      destinationCACertificate: ""
```

## Current documentation
https://github.com/ergon/airlock-helm-charts/blob/9e5aea4febf534622bf4544946ac9608e0c9ee87/charts/microgateway/README.md.gotmpl#L554

## Checklist
- [x] The issue contains all necessary information a third party requires to understand.
- [x] The documentation has already been checked.
