### ISSUE TITLE
[Bug] Empty route.hosts leads to no route being rendered despite route.enabled=true

### ISSUE THREAD

**Issue by ccremer** [ergon/airlock-helm-charts#52]
## Description
Empty `route.hosts` array leads to no Openshift Route object being rendered despite `route.enabled=true`

## To Reproduce
1. Create MWE `helmfile.yaml` with [helmfile](https://github.com/roboll/helmfile):
```yaml
repositories:
  - name: ergon
    url: https://ergon.github.io/airlock-helm-charts/
  - name: ealenn
    url: https://ealenn.github.io/charts/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: microgateway-test
    chart: ergon/microgateway
    version: 0.6.0
    values:
      - route:
          enabled: true
          hosts: []
```
2. `helmfile template` or `helmfile apply`

## Expected behavior

The route should be rendered, but leaving `spec.host` empty. OpenShift will generate a route host name if it's left empty. On Appuio for example it will use the "appuioapp.ch" domain name and certificate with a generated subdomain consisting of route name and namespace.

## Current behavior
The route is not being rendered at all, even with `route.enabled=true` Helm variable.

## Screenshots / Logs
If applicable, add screenshots or logs to help explain your problem.

## Additional information
- When did this behavior first occur? What has changed?
- Can the issue be reproduced? Does it occur on regular basis?

## Versions
 - Microgateway: irrelevant
 - Helm chart: 0.6.0
 - Helm client: 3.1.2
 - Kubernetes / Openshift: irrelevant

## Checklist
- [x] The issue contains all necessary information a third party requires to understand.
- [x] The documentation has already been checked.

**Comment by libuweber** [comment]
Empty host names can be specified using an empty string as hostname:
```yaml
route:
    enabled: true
    hosts:
      - ""
```
