### ISSUE TITLE
[Feature] Add image pull secret as a template, configurable via Helm parameters

### ISSUE THREAD

**Issue by ccremer** [ergon/airlock-helm-charts#55]
## Description
See https://github.com/ergon/airlock-helm-charts/tree/master/charts/microgateway#credentials-to-pull-image-from-docker-registry:
* Add the result of `kubectl create secret docker-registry docker-secret --docker-username=<username> --docker-password=<access_token>` as a Helm template into the Chart, parameterized with the credentials.

## Describe the solution you'd like
New Helm parameters, e.g.
```yaml
image:
  imagePullSecret:
    create: true
    registryUser: "" # my-docker-user
    registryToken: "" # my-docker-token-or-password
```
and a template (Pseudo-code):
```yaml
apiVersion: v1
stringData:
  .dockerconfigjson: {"auths":{"https://index.docker.io/v1/":{"username":"{{ .Values.image.imagePullSecret.registryUser }}","password":"{{ .Values.image.imagePullSecret.registryToken }}","auth":"{{ printf %s:%s .Values.image.imagePullSecret.registryUser .Values.image.imagePullSecret.registryToken | base64 }}"}}}
kind: Secret
metadata:
  name: ...
```

## Describe alternatives you've considered
When we want to have everything in YAML in a Git repository, one would need to create an extra Helm release (either via Helmfile or via some GitOps Operator) or manage the secret separately e.g. via some CI pipeline as a single step before applying the chart. These alternatives feel like a hack, it could be more integrated.

## Additional information
It seems that the microgateway image is clearly in a private repository. While most public Helm charts offer the possibility to add image pull secrets, they do not provide the template itself as it's rarely the case one needs them, since the images are very often in public registries. With Airlock microgateway, this is clearly not the case and a requirement to have access to the repository, so it may make sense to ease creation of the image pull secret by providing easy Helm parameters so the image pull secret is also managed with Helm.

Right now, the image pull secret needs to be manually created, but it would be nice if this could also be automated within the Chart.

What do you think?

## Versions
 - Microgateway: 1.0
 - Helm chart: 0.6.0
 - Helm client: v3.1.2
 - Kubernetes / Openshift: irrelevant

## Checklist
- [x] The issue contains all necessary information a third party requires to understand.
