### ISSUE TITLE
[Feature] Add dedicated port for health probes

### ISSUE THREAD

**Issue by ccremer** [ergon/airlock-helm-charts#58]
## Description
* Add a different container port listening for microgateway liveness- and readiness probes. The current `/healthz` endpoint intercepts any requests going to the backend (URL clash) and the endpoint is not configurable. In other words: If the backend also provides `/healthz` and needs to be publicly available, it's the microgateway that answers, not the backend.

## Describe the solution you'd like
deployment.yaml:
```yaml
      ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: metrics
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
...
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
```
service.yaml:
```yaml

spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
  - port: {{ .Values.service.tlsPort }}
    targetPort: https
    name: https
  - port: {{ .Values.service.metricsPort }}
    name: metrics
```
And maybe also a Route that is dedicated for the metrics, open for discussion.

## Describe alternatives you've considered
If the backend also provides the `/healthz` URL endpoint, the liveness and readiness probe should be configurable via Helm, so that the microgateway can answer health checks on a different endpoint. This way at least the user is able to remove the URL clash via configuration

## Additional information
* This would also allow flexibility if you are considering adding Prometheus metrics endpoint to the microgateway itself, to start providing means to create WAF insights with Dashboards like Grafana etc. The convention is to use `/metrics`, but the backend may also provide a `/metrics` endpoint, also creating a URL endpoint interception. Any prometheus instance scraping the microgateway does not need to connect to the public facing service ports 443 or 80 (8443 or 8080 resp.), but can rather scrape directly the metrics port inside the cluster, even if the backend is unreachable. If the Prometheus is in-cluster, the metrics port does not need to be publicly available via Ingress/Route for that, but it could be enabled if desired.

## Versions
 - Microgateway: 1.0
 - Helm chart: 0.6.0
 - Helm client: v3.1.2
 - Kubernetes / Openshift: irrelevant

## Checklist
- [x] The issue contains all necessary information a third party requires to understand.
