### ISSUE TITLE
[Bug] Simple DSL example cannot be rendered with Helm

### ISSUE THREAD

**Issue by ccremer** [ergon/airlock-helm-charts#59]
## Description
Following the example from README in https://github.com/ergon/airlock-helm-charts/tree/master/charts/microgateway#simple-dsl-configuration:
* There is a Helm chart render error in `microgateway/templates/configmap.yaml:91:29` when enabling `config.simple.mapping.deny_rules`, see below

## To Reproduce
1. Create a Helmfile:
```yaml
repositories:
  - name: ergon
    url: https://ergon.github.io/airlock-helm-charts/
  - name: ealenn
    url: https://ealenn.github.io/charts/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: microgateway-test
    namespace: ergo-25
    chart: ergon/microgateway
    version: 0.6.0
    values:
      - config:
          global:
            ip_header:
              trusted_proxies:
                - 10.0.0.0/28
          simple:
            mapping:
              entry_path: /
              operational_mode: integration
              deny_rules:
                - level: strict
                  enabled: true
                  exceptions:
                    - parameter_name:
                        pattern: ^content$
                        ignore_case: true
                      path:
                        pattern: ^/mail/
                      method:
                        pattern: ^POST$
```
2. Execute `helmfile template`

## Expected behavior
`microgateway/templates/configmap.yaml` can be rendered, so that the ConfigMap is producing a valid YAML to apply for Kubernetes

## Current behavior
The ConfigMap cannot be rendered due to a Gotemplate syntax error: `executing "microgateway/templates/configmap.yaml" at <$simple.mapping.deny_rules.enabled>: can't evaluate field enabled in type interface {}`

## Screenshots / Logs
```console
...
Templating release=microgateway-test, chart=/tmp/525002622/microgateway-test/0.6.0/ergon/microgateway/microgateway
in ./config-mwe.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: microgateway-test (22 bytes)
  3: /tmp/525002622/microgateway-test/0.6.0/ergon/microgateway/microgateway (75 bytes)
  4: --namespace (11 bytes)
  5: ergo-25 (7 bytes)
  6: --values (8 bytes)
  7: /tmp/values561474757 (20 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  coalesce.go:196: warning: cannot overwrite table with non table for deny_rules (map[enabled:true exceptions:[] level:standard log_only:false])
  coalesce.go:196: warning: cannot overwrite table with non table for deny_rules (map[enabled:true exceptions:[] level:standard log_only:false])
  Error: template: microgateway/templates/deployment.yaml:17:28: executing "microgateway/templates/deployment.yaml" at <include (print .Template.BasePath "/configmap.yaml") .>: error calling include: template: microgateway/templates/configmap.yaml:91:29: executing "microgateway/templates/configmap.yaml" at <$simple.mapping.deny_rules.enabled>: can't evaluate field enabled in type interface {}
```

## Additional information
The faulty code is probably here somewhere: https://github.com/ergon/airlock-helm-charts/blob/master/charts/microgateway/templates/configmap.yaml#L91

## Versions
 - Microgateway: irrelevant
 - Helm chart: 0.6.0
 - Helm client: v3.1.2
 - Kubernetes / Openshift: irrelevant

## Checklist
- [x] The issue contains all necessary information a third party requires to understand.
- [x] The documentation has already been checked.
