### ISSUE TITLE
[Feature] CI: Use imageCredentials to create the dockerregcred

### ISSUE THREAD

**Issue by jbe99** [ergon/airlock-helm-charts#84]
## Description
At the moment, the Docker registry credential is created separately in the CI pipeline for installing the helm chart. 
This should happen directly during the ct install with imageCredentials values. 

## Additional information
This is currently not possible because ct uses the same extra-args for the uninstall of the helm chart as for the install. 
Since --set is invalid for uninstall, there is an error. 

## Used Code
ci.yaml
```
      - name: Create Secrets
        run: |
          kubectl cluster-info
          kubectl create secret generic microgatewaysecrets --from-literal=license="${{ secrets.WAF_LICENSE }}" --from-literal=passphrase="${{ secrets.WAF_PASSPHRASE }}"
      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml --helm-extra-args "--set imageCredentials.username=${{ secrets.DOCKER_USER }} --set imageCredentials.password=${{ secrets.DOCKER_USER_TOKEN }}"

```
testing-values.yaml
```
config:
  generic:
    existingSecret: "microgatewaysecrets"
imageCredentials:
  enabled: true
redis:
  enabled: true
echo-server:
  enabled: true
ingress:
  enabled: true
```

## Dependency:
https://github.com/helm/chart-testing/issues/322

## Checklist
- [x] The issue contains all necessary information a third party requires to understand.
